version: '3'

services:
  # MySQL
  db:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recepie_finder
      MYSQL_USER: renas
      MYSQL_PASSWORD: ustek
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/sql:/docker-entrypoint-initdb.d'

