cluster.name: "recipe-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

# Settings below are Elasticsearch configuration details reserved for DGC search to work properly for all environments
# and all customers/backups (also production).
# For environment-dependent settings look into docker compose file.
#bootstrap.memory_lock: 'true'
#bootstrap.system_call_filter: 'false'
#node.max_local_storage_nodes: 8
#cluster.routing.allocation.disk.threshold_enabled: 'false'
#action.auto_create_index: '.*'